const data = {
  products: [
    {
      _id: "1",
      name: "2Pac T-Shirt",
      category: "T-Shirts",
      image: "/images/playera5.webp",
      price: 120,
      brand: "StreetWear",
      rating: 0.5,
      numReviews: 10,
      description: "Playera de alta calidad.",
    },
    {
      _id: "2",
      name: "Lacoste T-Shirt",
      category: "T-Shirts",
      image: "/images/mochila1.jpg",
      price: 320,
      brand: "StreetWear",
      rating: 4.5,
      numReviews: 8,
      description: "Mochila 1.",
    },
    {
      _id: "3",
      name: "Nike Slim Pants",
      category: "Pants",
      image: "/images/mochila2.jpg",
      price: 420,
      brand: "Nike",
      rating: 5,
      numReviews: 4,
      description: "Mochila de alta calidad.",
    },
    {
      _id: "4",
      name: "Mochila para skate",
      category: "Mochilas",
      image: "/images/mochila3.jpg",
      price: 500,
      brand: "Nike",
      rating: 3,
      numReviews: 7,
      description: "Mochila de alta calidad.",
    },
  ],
};

export default data;
